rust-lang/annotate-snippets-rs

examples/expected_type.rs, examples/footer.rs, examples/format.rs, examples/multislice.rs, src/display_list/structs.rs, src/formatter/mod.rs, tests/fixtures.rs, tests/formatter.rs
With the current diagnostics emitter of Rust, the `-Z ui-testing` flag
allows to 'anonymize' line numbers in the UI test output.
This means that a line such as:
2 |     concat!(b'f');
is turned into:
LL |     concat!(b'f');
This is done because it makes the diff of UI test output changes much
less noisy.
To support this with `annotate-snippet`, we add a second parameter to
`DisplayListFormatter` that, when true, replaces the line numbers in the
left column with the text `LL`. The replacement text is always `LL` and
it does not affect the initial location line number.
In the new `annotate-snippet` emitter in rustc, we can then use this
parameter depending on whether the `-Z ui-testing` flag is set or not.
Closes #2 
cc https://github.com/rust-lang/rust/issues/59346
=> Add option to anonymize line numbers

src/formatter/mod.rs, tests/formatter.rs
This expands the logic for replacing line numbers with `LL` so that line
numbers are only replaced, when they are actually provided.
When `lineno` is `None`, no `LL` should be shown in the output.
=> Fix too many anonymized line numbers

src/snippet.rs
=> Derive PartialEq for snippet::AnnotationType

src/display_list/from_snippet.rs, tests/fixtures/no-color/multiline_annotation.txt, tests/fixtures/no-color/multiline_annotation2.txt, tests/fixtures/no-color/simple.txt
This is a small change to start column numbers from 1 instead of 0.
Issue: #17
=> Start column numbers from 1

src/display_list/from_snippet.rs, tests/fixtures/no-color/multiline_annotation3.txt, tests/fixtures/no-color/multiline_annotation3.yaml
Fixes the error described in #16. Previously, when a single character of
an annotation overflows to a new line, the DisplayList would incorrectly
consider that character on the same line. This change fixes this and
adds a new fixture test for this case.
=> Fix single char overflow display issue

benches/simple.rs, examples/expected_type.rs, examples/footer.rs, examples/format.rs, examples/multislice.rs, src/display_list/from_snippet.rs, src/display_list/mod.rs, src/display_list/structs.rs, src/formatter/mod.rs, src/formatter/style.rs, src/snippet.rs, src/stylesheets/color.rs, src/stylesheets/no_color.rs, tests/diff/mod.rs, tests/dl_from_snippet.rs, tests/fixtures/no-color/multiline_annotation.yaml, tests/fixtures/no-color/multiline_annotation2.yaml, tests/fixtures/no-color/multiline_annotation3.yaml, tests/fixtures/no-color/multiple_annotations.yaml, tests/fixtures/no-color/simple.yaml, tests/fixtures_test.rs, tests/formatter.rs, tests/snippet/mod.rs
In `test_i26` what should be the output?
panic or anything other than the label disappearing?
I would panic or even refactor to TryFrom. What you prefer
Fix #26
=> Fix SourceAnnotation ranges and refactor to `std::fmt::Display`

Cargo.toml, src/formatter/mod.rs, src/formatter/style.rs, src/stylesheets/color.rs, src/stylesheets/no_color.rs, tests/diff/mod.rs
This PR eliminates the need to reallocate while formatting. 
For this I have forked the `ansi_term` library to refactor to `fmt::Display` allowing to introduce flow with a closure that takes the current formatter as argument. 
It will depend on `yansi-term` instead of` ansi_term`, which I will keep.
=> Fix to no copy when format with yansi_term

src/formatter/mod.rs, src/stylesheets/mod.rs
Differ `Cargo.toml` and Rust attributes names
=> Fix feature attributes "ansi_term" to "color"

src/display_list/from_snippet.rs, tests/fixtures/no-color/issue_9.toml, tests/fixtures/no-color/issue_9.txt, tests/snippet/mod.rs
=> Removing duplicate Slice origins and surrounding empty lines

Cargo.toml, README.md, src/display_list/from_snippet.rs, src/display_list/structs.rs, src/formatter/mod.rs, src/formatter/style.rs, src/lib.rs, src/stylesheets/mod.rs, tests/dl_from_snippet.rs, tests/fixtures/no-color/strip_line.toml, tests/fixtures/no-color/strip_line.txt, tests/fixtures/no-color/strip_line_non_ws.toml, tests/fixtures/no-color/strip_line_non_ws.txt, tests/snippet/mod.rs
Closes #8 
Is the same `Margin` as rustc but zero copy
Closes #35
=> Add strip code to the left and right for long lines

src/formatter/mod.rs, tests/fixtures/no-color/strip_line_char.toml, tests/fixtures/no-color/strip_line_char.txt
I had made an error to strip code in margin. In cases such as coverage, it could panic.
=> Fix character split when strip code

src/display_list/from_snippet.rs, tests/fixtures/no-color/multiline_annotation.toml, tests/fixtures/no-color/multiline_annotation2.toml
Implements the fix described in #41.
Fixes #41
=> fix off by one error in multiline highlighting

src/display_list/from_snippet.rs, tests/formatter.rs
Hi there.
We're using this crate in [denoland/deno_lint](https://github.com/magurotuna/deno_lint) to display pretty diagnostics of the linter. By chance, I found that this crate doesn't work well if the source includes double width characters like:
```ts
const a = "こんにちは";
```
Specifically, if we attempt to point to `は` in this snippet by passing `(15, 16)` as range, annotate-snippets will give us:
```
|
1 | const a = "こんにちは";
|                ^
|
```
where obviously `^` points to the wrong position.
These characters take up twice the size of ordinary characters like the alphabet, so displaying annotation for them requires special handling, which I implemented in this patch.
=> Fix display of annotation for double width characters

README.md
The .com URL now returns "No Results Found". Not sure if there's a better solution here.
=> Switch Travis CI URL back to .org

src/display_list/from_snippet.rs, tests/fixtures/no-color/issue_52.toml, tests/fixtures/no-color/issue_52.txt
This pr changes the `format_header` function to use the line number that is already stored in `DisplayLine` instead of (wrongly) recomputing it.
Fixes #52
=> Show correct line numbers when fold ist set to true, fixes #52

src/display_list/from_snippet.rs, tests/dl_from_snippet.rs
In #53 I reported the issue that `__` in titles gets parsed specially. This feature isn't documented anywhere, and doing a bit of git archaeology, I get lost 4 years ago with phrases like "more tests" adding the code. I can't figure out why someone would want this feature, but assume there was a reason when it was added, however, I'm not sure it is still useful. There doesn't seem any way to opt out of this feature, and as a result, error messages containing `__` get dropped (which is super confusing).
In the absence of feedback as the right way to proceed, I've made a diff removing the feature entirely. The alternative would be to document the feature, explain why it's useful, and explain how to avoid it (an alternative API? an escaping scheme?).
=> Remove parsing of __ in title strings, fixes #53

Cargo.lock, Cargo.toml, README.md
This PR:
- Removes unneeded badges from `Cargo.toml` and `README.md`
- Moves to Edition `2021`
- Sets MSRV to `1.70.0` to [match CI](https://github.com/rust-lang/annotate-snippets-rs/blob/01ad63a88e53fd3cebe426f2ce8365609a4efb55/.github/workflows/ci.yml#L60)
- Sorted the dependencies alphabetically
- Fully specified dependency versions
- Updated `criterion` to the newest version 
Note: Updating `edition` and `rust-version` is ["Possibly" a semver-breaking](https://doc.rust-lang.org/cargo/reference/semver.html#env-new-rust) change. It is recommended that this is treated as a minor change, and since this is a `pre-1.0.0` crate, we should bump the patch version when this is released, that is `0.9.3`.
Note: I could not update `toml` to the newest version as it stopped supporting borrowing …
=> Cleanup and updates

.github/renovate.json5, .github/workflows/ci.yml, Cargo.toml
Once infra enables RenovateBot, this will
- Create individual PRs for breaking changes
- Combined PRs for compatible changes
This also auto-updates MSRV, like cargo and clap do, to avoid stagnation and people getting the wrong impression of the MSRV policy from that stagnation.  This also avoids contributors being hesitant about what justifies updating MSRV.
=> chore(ci): Auto-update versions

CHANGELOG.md, Cargo.lock, Cargo.toml
This PR updates the `CHANGELOG.md` in preparation for `0.10.0`, as well as bumps the version number to `0.10.0`. I have tried my best to capture what changes were made and added a note saying that `annotate-snippets` is in the middle of a rewrite and that there could be more breaking changes in future releases.
Note: I have not created a tag for `0.10.0` (I am unsure how to create one or if I have permission to do so), so the updated links will not work until one is created.
Note: This release will help unblock work on a diagnostic system for `cargo`. It will allow work to be done while this crate is being evolved.
=> Annotate snippets 0.10.0

README.md
In #67 and  #69, I missed updating the `README.md` to use `Renderer`; this PR fixes that.
Note: Once this is merged, I will try to adjust the [`0.10.0`](https://github.com/rust-lang/annotate-snippets-rs/releases/tag/0.10.0) tag to the merge commit, but I am uncertain if I can.
=> chore: Update `README.md` example to use `Renderer`

src/renderer/mod.rs
This PR makes it so that we match `rustc`'s output regarding colors. See [here](https://github.com/rust-lang/rust/blob/e51e98dde6a60637b6a71b8105245b629ac3fe77/compiler/rustc_errors/src/emitter.rs#L2676-L2723) and [here](https://github.com/rust-lang/rust/blob/e51e98dde6a60637b6a71b8105245b629ac3fe77/compiler/rustc_errors/src/lib.rs#L1768-L1787) for `rustc`'s current color implementation.
Note: Where `rustc` uses `set_intense(true)`, that is the same as `Bright<color>` in `anstyle`.
Note: Most things are `BOLD` as `rustc` eventually sets most things bol (see the first link).
=> fix: Match rustc's colors

src/renderer/display_list.rs, tests/fixtures/no-color/one_past.toml, tests/fixtures/no-color/one_past.txt
Being able to highlight one past the end of the given source if the source provided is from `.lines()` (and got its newline stripped) or is the last line in the file and you want to highlight the next "character". `cargo` needs something to do this, so it doesn't have to remember to add a new line in either scenario.
=> fix: Allow highlighting one past end

Cargo.toml, src/lib.rs, src/renderer/mod.rs
In [cargo#13461](https://github.com/rust-lang/cargo/pull/13461#discussion_r1501136340), it was noticed that the default colors being platform-specific made testing colored output quite challenging. This PR adds a feature that makes the colors the same across the board, which should be enabled when testing colored output.
=> feat: Add feature for testing colored output easier

Cargo.lock, Cargo.toml, benches/simple.rs, examples/expected_type.rs, examples/footer.rs, examples/format.rs, src/renderer/display_list.rs, src/snippet.rs, tests/fixtures/deserialize.rs, tests/formatter.rs
BREAKING CHANGE: This switches from char spans to byte spans
This PR is a draft implementation to address #77. While I think I fixed every issue in moving from char spans to byte spans, I am not entirely certain. I may look into adding more tests to ensure we are doing the write thing. This also doesn't address the fact that people could pass in char spans when updating the version, not realizing the change. We could do something to make it more apparent but I am not sure what that would be.
=> fix!: Take in byte spans

benches/simple.rs, examples/expected_type.rs, examples/footer.rs, examples/format.rs, examples/multislice.rs, src/lib.rs, src/renderer/display_list.rs, src/renderer/mod.rs, src/snippet.rs, tests/fixtures/deserialize.rs, tests/fixtures/no-color/issue_52.toml, tests/fixtures/no-color/multiline_annotation.toml, tests/fixtures/no-color/multiline_annotation2.toml, tests/fixtures/no-color/multiline_annotation3.toml, tests/fixtures/no-color/multiple_annotations.svg, tests/fixtures/no-color/multiple_annotations.toml, tests/fixtures/no-color/strip_line.toml, tests/fixtures/no-color/strip_line_char.toml, tests/fixtures/no-color/strip_line_non_ws.toml, tests/formatter.rs
BREAKING CHANGE: Snippets must be created using the builder pattern
This PR makes it so that `Snippet`s must be created via a builder pattern, as described in #87. This should make it easier to change the internal API without making breaking changes. It also appears to help in code readability and size but that is determined by personal preference.
fixes #87
=> feat!: Move to builder pattern for snippet creation

Cargo.lock, Cargo.toml, README.md, examples/expected_type.rs, examples/expected_type.svg, examples/footer.rs, examples/footer.svg, examples/format.rs, examples/format.svg, examples/multislice.rs, examples/multislice.svg, src/lib.rs, tests/examples.rs
We now pull from an example
- We verify it builds (wasn't doing that with README)
- We show the output for the actual code (couldn't do that from a
rustdoc code fence)
=> docs: Shift example code from README to lib.rs

benches/simple.rs, examples/expected_type.rs, examples/footer.rs, examples/format.rs, examples/multislice.rs, src/lib.rs, src/renderer/display_list.rs, src/renderer/mod.rs, src/snippet.rs, tests/fixtures/deserialize.rs, tests/fixtures/main.rs, tests/fixtures/no-color/issue_52.toml, tests/fixtures/no-color/issue_9.toml, tests/fixtures/no-color/multiline_annotation.toml, tests/fixtures/no-color/multiline_annotation2.toml, tests/fixtures/no-color/multiline_annotation3.toml, tests/fixtures/no-color/multiple_annotations.toml, tests/fixtures/no-color/one_past.toml, tests/fixtures/no-color/simple.toml, tests/fixtures/no-color/strip_line.toml, tests/fixtures/no-color/strip_line_char.toml, tests/fixtures/no-color/strip_line_non_ws.toml, tests/formatter.rs
This is a batch API change from talking to @Muscraft about what would make the clearer, what will make it more easily adapt to rustc, and what will make it better encoded the design in the type system.
Renames:
- `Snippet` -> `Message`
- `Slice` -> `Snippet`
- `Slice::new` to `Snippet::source`
- `SourceAnnotation` -> `Annotation`
- `AnnotationType` -> `Level`
Other breaking changes:
- `Snippet::line_start` is now defaulted to `1`  instead of required
- Create `Message` from `Level`
- Create `Annotation` from `Level`
- `Annotation::label` is now optional
New:
- Bulk-add functions to make it simpler to use builder API for automated conversion
What wasn't done:
- Deferred: Switch `Annotation` from using `Level` to a `Style { Level, Neutral, Added, Removed }`
- Deferred: Remove `footer` or …
=> fix!: Clarify Snippet API

examples/footer.rs, src/renderer/display_list.rs, src/snippet.rs, tests/fixtures/deserialize.rs
Note: the focus of this is not to get full parity with rustc but to get the API in place for us to later get parity with rustc.
Fixes #96
=> fix!: Generalize footer to be any Message 

Cargo.lock, Cargo.toml, src/renderer/display_list.rs, tests/fixtures/no-color/ensure-emoji-highlight-width.svg, tests/fixtures/no-color/ensure-emoji-highlight-width.toml, tests/formatter.rs
In #90, I made the mistake of thinking bytes and character widths were the same thing, and boy, was I very wrong. This PR addresses this problem and ensures that we are properly dealing with characters with different widths from the number of bytes they are made up of.
=> fix: Make spans work with single width emojis

src/renderer/display_list.rs, src/renderer/margin.rs, src/renderer/mod.rs, tests/fixtures/deserialize.rs, tests/fixtures/no-color/strip_line.toml, tests/fixtures/no-color/strip_line_char.toml, tests/fixtures/no-color/strip_line_non_ws.svg, tests/fixtures/no-color/strip_line_non_ws.toml
`Margin` was being utilized for a whole `Message` when it really should be per `Snippet`, since that is what is displayed together. `Margin` should also be calculated by `annotate-snippets` and not passed in, as we know how to figure everything out.
To fix these problems, this PR does the following:
- Grouped a `Snippet`'s `DisplayLine`s together into a `DisplaySet` so all lines to be rendered for a `Snippet` are kept together
- Made annotations be a field in `DisplayLine`, so they can reference information about the line. This will also help us in the future to be able to fold annotations into one line where possible, as well as other future rendering improvements
- Made it so that the `Margin` for each `DisplaySet` is created internally, allowing for better formatting
- Replaced the …
=> Fix margin

examples/expected_type.svg, src/renderer/display_list.rs, tests/fixtures/no-color/fold_ann_multiline.svg
Before, we elided all small sets of unhighlighted lines and then partially elided large sets of unhighlighted lines (favoring the start).
In contrast, rustc shows 2 lines of context, split between the start and end of the fold.
If there are 3 unhighlighted lines, it just skips folding. This makes a lot more sense.
See https://github.com/rust-lang/rust/blob/2627e9f3012a97d3136b3e11bf6bd0853c38a534/compiler/rustc_errors/src/emitter.rs#L1878C17-L1939C18
In contrast to rustc, I made the amount of context a variable to make the intent clearer and to open the door to it being configurable.
=> fix(render): Fold like rustc

src/lib.rs, src/renderer/mod.rs, src/snippet.rs
While working on some changes for `cargo`, I encountered an issue where `Debug` was not implemented for `Renderer`. To fix this, I derived `Debug` for all public types and set [`missing-debug-implementations`](https://doc.rust-lang.org/stable/rustc/lints/listing/allowed-by-default.html#missing-debug-implementations) to `warn`, so this issue does not pop up again in the future.
=> Add derive debug for public types

Cargo.lock, Cargo.toml
With the upcoming MSRV-aware resolver, I've been experimenting with lower MSRVs.
This will directly benefit `winnow` in allowing it to have examples of having parse errors rendered with annotate-snippets.
=> chore: Drop MSRV to 1.65

src/renderer/display_list.rs, tests/fixtures/no-color/ann_multiline2.svg, tests/fixtures/no-color/ann_multiline2.toml, tests/fixtures/no-color/fold_ann_multiline.svg, tests/formatter.rs
There have been a number of problems recently with annotating line endings:
- #130
- #117
I went ahead and tried my best to fix all of the current problems with annotating line endings, and in doing so, #116 appears to be fixed as well.
The two root problems were that we never really supported highlighting the end of a line in multiline spans, and even in cases where we did support highlighting the end of the line, we only supported highlighting the first of the line endings, if the line ended with `\r\n`.
=> Fix annotating line endings

tests/fixtures/main.rs
While working on #143, I noticed that fixture test names were missing the "module" (folder) before the name, which usually gets added for normal tests in folders. While this isn't a big deal now, if other test folders get added in the future, it will make it easier to find the failure.
Before:
After:
=> Show fixture test location

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, benches/bench.rs, benches/simple.rs, src/renderer/display_list.rs
Inspired by https://purplesyringa.moe/blog/i-sped-up-serde-json-strings-by-20-percent/
```console
$ cargo bench && cargo bench -F simd
Compiling annotate-snippets v0.11.2 (/home/epage/src/personal/annotate-snippets-rs)
Finished `bench` profile [optimized] target(s) in 0.99s
Running unittests src/lib.rs (target/release/deps/annotate_snippets-b51bb37991a7f496)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running benches/bench.rs (target/release/deps/bench-468ba612503afee1)
Timer precision: 18 ns
bench         fastest       │ slowest       │ median        │ mean          │ samples │ iters
├─ fold                     │               │               │               │         │
│  ├─ 0       1.911 µs      │ 19.44 µs      │ 1.943 …
```
=> perf: Offer 'simd' feature for faster folding 

.github/workflows/ci.yml, .github/workflows/pre-commit.yml, .github/workflows/rust-next.yml, Cargo.toml, LICENSE-APACHE, LICENSE-MIT, release.toml, src/renderer/display_list.rs, tests/fixtures/main.rs
I needed to update the pre-commit Action and decided this would make it easier
=> chore: Adopt '_rust/main' template

Cargo.lock, Cargo.toml, tests/fixtures/deserialize.rs, tests/fixtures/main.rs
We have been stuck on `toml@0.5.11` for quite some time, as   [`toml@0.6.0` dropped support for deserializing to borrowed types](https://github.com/toml-rs/toml/blob/b05e8c489be8ebfc0acacc1ec3556d95cd8d2198/crates/toml/CHANGELOG.md#compatibility-7), which we were utilizing for fixture tests. To make it so I could update the `toml` version, I removed the use of borrowed types from `Fixture`.
=> Update toml to 0.8.0

src/renderer/display_list.rs, tests/formatter.rs
This PR fixes an issue in the computation of the position in the origin file. When a highlighted section starts at the beginning of the line, the origin position used to point to the end of the previous line, instead of the start of the current line. This resulted in outputs like this:
```
error: title
--> origin.txt:2:4
|
1 | aaa
2 | bbb
3 | ccc
| ^^^ annotation
4 | ddd
|
```
Here `origin.txt:2:4` is wrong, it should be `origin.txt:3:1`, which actually matches the highlighted setting.
As a drive-by fix, 21645ad032dd9117d811db57a5740b6a6406f94a fixes `EndLine`, which was used incorrectly in multiple places that happened to cancel out.
=> Fix origin position computation

.github/renovate.json5, .github/workflows/ci.yml, Cargo.toml, src/renderer/display_list.rs
This also fixes clippy lints to prep for #163
=> chore: Update from _rust template

release.toml
#147 changed the branch allowed release branch from `master` to `main`. The allowed release branch should be `master` as that is the default branch.
=> chore: Make master the allowed release branch

src/renderer/display_list.rs
`unhighlighed` -> `unhighlighed`
=> chore: Fix typos

examples/custom_level.svg, examples/footer.svg, examples/highlight_title.svg, src/level.rs, src/renderer/mod.rs, src/snippet.rs, tests/formatter.rs
This is another change related to matching `rustc`'s output. In this case, we were giving `ElementStyle::MainHeaderMsg` to the first `Title` of each `Group`, when it should only be applied to the first `Title` of a `Message`.
=> fix: Only bold the first title of a message

src/renderer/source_map.rs, tests/formatter.rs, tests/rustc_tests.rs
Note: This is another change related to matching rustc's output
=> fix: Match rustc's multiline reordering

src/renderer/source_map.rs, tests/color/ann_multiline2.term.svg, tests/color/simple.term.svg, tests/formatter.rs, tests/rustc_tests.rs
Note: This is another change related to matching `rustc`'s output
=> fix: Match how rustc handles annotating newlines

src/renderer/mod.rs, src/snippet.rs, tests/rustc_tests.rs
=> fix!: Remove of Origin::label

src/renderer/source_map.rs, tests/formatter.rs, tests/rustc_tests.rs
`rustc` will occasionally give us a `Snippet` with an empty source and an `Annotation` with the span `0..0`, which causes `annotate-snippets` to panic. The root cause of the panic is that a few places in `SourceMap` expect at least one `LineInfo`, when none are created for an empty source. To fix this, I made it so when we are given an empty source, we add a single "empty" `LineInfo`, with the appropriate `line_index`.
<hr>
When looking into how to fix this, I noticed that `rustc` [doesn't show the annotation](https://github.com/rust-lang/rust/blob/36b21637e93b038453924d3c66821089e71d8baa/tests/ui/include-macros/mismatched-types.stderr#L1-L4) even though there is one that could be displayed. Because of this, I felt it was best to diverge from how `rustc` would render this and show the …
=> fix: Ensure empty sources have one "line"

src/renderer/styled_buffer.rs, tests/rustc_tests.rs
I somehow [missed a commit](https://github.com/rust-lang/rust/pull/137757/commits/cb82b79f02b79620f766d94c0e4a8c20a3ce23ee) when backporting [rust#137757](https://github.com/rust-lang/rust/pull/137757) in #213. This PR backports the missed commit.
(I only noticed that I missed this commit when looking for solutions for the exact problem that it fixed)
=> fix: Don't attempt out of bounds buffer replacments

tests/formatter.rs
When working on a fix for an issue, it caused changes to `multiline_removal` and `multiline_replacement`, which I found odd, so I dug into why that was happening and found that the suggestion spans for both were one byte wider (34 vs 33) than the span of the [test they were based on](https://github.com/rust-lang/rust/blob/5de8e6edfcc747930891a0adc8e90608776dbe54/tests/ui/suggestions/removal-of-multiline-trait-bound-in-where-clause.stderr#L1-L28). Removing this extra width makes it so that `multiline_removal`'s suggestion matches the original test.
=> test: Adjust spans to match original test spans

src/renderer/mod.rs, tests/formatter.rs
Before this change, all multi-line secondary titles were aligned as if their level text was `note`, regardless of their actual level text. This made subsequent lines of the title start before the first one. This PR ensures that level text is always taken into account when rendering subsequent lines of a multi-line title.
=> fix: Align multi-line secondary titles by level text

src/level.rs, src/renderer/mod.rs, src/renderer/source_map.rs, src/snippet.rs, tests/formatter.rs
=> fix: Take Into<Cow> instead of &str

examples/elide_header.rs, examples/elide_header.svg, src/renderer/mod.rs, src/snippet.rs, tests/examples.rs
This should allow users to create a `Group` without a `Title` and control the primary `Level` for that `Group`.
=> feat: Allow setting the primary level for a group

benches/bench.rs, examples/custom_error.rs, examples/custom_level.rs, examples/expected_type.rs, examples/format.rs, examples/highlight_source.rs, examples/highlight_title.rs, examples/id_hyperlink.rs, examples/multislice.rs, src/renderer/mod.rs, src/snippet.rs, tests/color/fold_ann_multiline.rs, tests/color/fold_bad_origin_line.rs, tests/color/fold_leading.rs, tests/color/fold_trailing.rs, tests/color/multiline_removal_suggestion.rs, tests/color/multiple_annotations.rs, tests/formatter.rs, tests/rustc_tests.rs
=> chore!: Make fold the default

examples/custom_error.rs, examples/custom_level.rs, src/level.rs, tests/formatter.rs
The goal for this is to make the intent clearer as `text` could be interpreted as the title's text (or message when we add that)
=> fix: Rename `Label::ERROR.text().title()` with `Label::ERROR.with_name().title()`

examples/highlight_message.rs, src/level.rs, src/renderer/mod.rs, src/renderer/styled_buffer.rs, src/snippet.rs, tests/color/multiline_removal_suggestion.rs, tests/formatter.rs, tests/rustc_tests.rs
This does include one API change along the way, to rename `Origin::new` to `Origin::path` to match `Snippet::source`.
I opportunistically used existing examples with screenshots but didn't force the issue.  There is always the trade off because we can't elide content in those.
=> docs: Clarify usage

src/level.rs, src/snippet.rs
#245 made `clippy::needless_doctest_main` fire locally, and this fixes those warnings.
=> fix: Address clippy::needless_doctest_main

tests/formatter.rs
In #176, it was noticed that how we rendered empty spans at the start of a line changed without reason. As an attempt to catch any future changes, I added the example in the issue as a test.
=> test: Add a test for annotating an empty span at the start of a line

src/renderer/source_map.rs, tests/formatter.rs
When given a patch span beyond the end of the source, we silently allow it to work. Conversely, when we are given an annotation span beyond the end of the source, we panic. This PR makes it so that we consistently panic when given spans beyond the end of a source.
Note: This PR is only meant to make `annotate-snippets` behave consistently and does not intend to delve into what the correct response should be.
=> fix!: Panic if Patch span is beyond the end of buffer

src/renderer/mod.rs, tests/formatter.rs
When `Padding` is last in a `Group`, it always renders as `|` when it really should have "closed" the group off. This problem was extremely noticeable with `OutputTheme::Unicode`.
=> fix: Render Padding as end col separator if last in Group

src/renderer/mod.rs, tests/rustc_tests.rs
While working on `rustc`, I saw that `annotate-snippets` and `rustc` had different outputs for [`unsafe_extern_suggestion`](https://github.com/rust-lang/rust/blob/f838cbc06de60819faff3413f374706b74824ca2/tests/ui/rust-2024/unsafe-extern-blocks/unsafe-extern-suggestion.rs). I spent some time digging into this, and it turns out we did not match how `rustc` handled overlaps. Some of the ways I attempted to fix this divergence caused [`alloc_error_handler_bad_signature_2`](https://github.com/rust-lang/rust/blob/f838cbc06de60819faff3413f374706b74824ca2/tests/ui/alloc-error/alloc-error-handler-bad-signature-2.rs) and [`str_escape`](https://github.com/rust-lang/rust/blob/f838cbc06de60819faff3413f374706b74824ca2/tests/ui/str/str-escape.rs) to regress, so I figured I would add them to help catch …
=> fix: Match rustc's annotation overlap

src/renderer/mod.rs, tests/formatter.rs
While working on the suggestion unicode output, I noticed we were still left-aligning suggestion line numbers. This PR makes it so we right-align the suggestion line numbers, making them match the snippet line numbers.
=> fix: Right align suggestion line numbers

src/renderer/mod.rs, tests/formatter.rs
This specialization is a remnant of an old usage/implementation of a `Level` with no name, and should've been removed.
=> fix: Don't specialize continuations for level's with no name

examples/struct_name_as_context.rs, examples/struct_name_as_context.svg, src/renderer/source_map.rs, src/snippet.rs, tests/examples.rs, tests/formatter.rs
This PR makes it so that you can "annotate" text with `AnnotationKind::Visible` to keep it from getting folded, allowing you to keep some lines around as context without underlining them with annotation characters.
```
error: functions are not allowed in struct definitions
--> $DIR/struct-fn-in-definition.rs:9:5
|
LL | struct S {
...
LL |     fn foo() {}
|     ^^^^^^^^^^^
|
= help: unlike in C++, Java, and C#, functions are declared in `impl` blocks
```
=> feat: Add a way to keep lines with no annotations

src/renderer/mod.rs, src/snippet.rs, tests/color/multiline_removal_suggestion.term.svg, tests/rustc_tests.rs
#261 made it so `primary` is controlled by element order, which left `Origin::primary` in an odd spot, as it could control the type of file start for an `Origin` when that should be determined by element order. To fix this issue, I removed `Origin::primary`.
=> Remove origin primary

src/renderer/mod.rs, tests/color/main.rs, tests/color/primary_title_second_group.rs, tests/color/primary_title_second_group.term.svg
Looking back at my PR switching to `secondary_title` (#282), I realized that none of the SVGs changed, which seemed odd to me as `primary_title` should be bolded every time. After looking into it a bit, I realized that `annotate-snippets` [would only use bold text for titles that are in the first group](https://github.com/rust-lang/annotate-snippets-rs/blob/b9dc9e5b6f713aaef36e5c915990e63e52ecb4bb/src/renderer/mod.rs#L222-L226) regardless of whether they were `primary` or `secondary`. This is a bug as `annotate-snippets` should respect `primary_title` and always bold its text, no matter the position of the `Group` it is in.
=> fix: Always style primary_title

Cargo.toml
The "memchr" feature does nothing on its own.
=> Remove accidental, undocumented `memchr` feature

examples/multislice.svg, src/renderer/mod.rs, tests/color/ann_multiline2.term.svg, tests/color/multiple_annotations.term.svg, tests/formatter.rs
If the last line in a `Snippet` did not contain an `Annotation` and nothing came after it, the code window would not get closed. This PR changes it so we close the window in that specific case.
=> fix: Handle window close for lines with no annotations

tests/color/highlight_source.ascii.term.svg, tests/color/highlight_source.rs, tests/color/highlight_source.unicode.term.svg, tests/color/main.rs
This PR adds a test showing how each `AnnotationKind` gets colored by `highlight_source`. This should hopefully help us catch any unwanted changes to how they are colored.
=> test: Highlight source on all AnnotationKind
